### PR TITLE
Calibrate to air after 10sec warmup

### PR DESCRIPTION
**Pull request by frauzufall**

### CODE REVIEW

**Comment by beniroquai** [comment]
Regarding calibration, do you think it's worth thinking about triggering a calibration run by "reversing" the flow?

**Comment by frauzufall** [comment]
@beniroquai yes, I think that's a great idea! Here is how it could look like:
- clearly indicate on the lid of the device which way is for measuring and which for calibration (i.e. `→ measurement` and `calibration 100% ←`, happy to provide an SVG, I don't know yet how to integrate it in the print files)
- once the device measures negative flow, a countdown is shown (`30s until calibrating to 100%..`) once the countdown is over, the device is calibrated to use the current voltage of the O2 sensor for 100%
- once the calibration countdown is over, another countdown starts (`10s to keep calibration after restart..`  ) once this countdown is over, we store the calibration value permanently - the ESP32 seems to have flash storage that we can use so that the calibration can be used after restarting the device
- both countdowns are canceled if the flow is not negative anymore
- if the second "permanent storage" countdown is canceled, the 100% measurement calibration will only be used for this runtime - after restarting, the device would go back to automatically calibrate to 21% after restarting the device.

These would be two use cases:
- to calibrate permanently to 100%, attach 100% O2 flow to the opposite side and wait until both countdowns are over
- to reset it to 21% air calibration after launching the device, attach any kind of flow to the opposite side, wait until first countdown is over, disconnect flow, restart device

.. what do you think?

**Comment by beniroquai** [comment]
```
clearly indicate on the lid of the device which way is for measuring and which for calibration (i.e. → measurement and calibration 100% ←, happy to provide an SVG, I don't know yet how to integrate it in the print files)
```

Good point! 
How about we engrave more text on the lid?
image

**Comment by beniroquai** [comment]
> * once the device measures negative flow, a countdown is shown (`30s until calibrating to 100%..`) once the countdown is over, the device is calibrated to use the current voltage of the O2 sensor for 100%

Yes brilliant! We should keep recording the values over ~5seconds and get the average value. 

> * once the calibration countdown is over, another countdown starts (`10s to keep calibration after restart..`  ) once this countdown is over, we store the calibration value permanently - the ESP32 seems to have flash storage that we can use so that the calibration can be used after restarting the device

Exactly, it has flash, never used it, but it's cool! 

> * both countdowns are canceled if the flow is not negative anymore
> * if the second "permanent storage" countdown is canceled, the 100% measurement calibration will only be used for this runtime - after restarting, the device would go back to automatically calibrate to 21% after restarting the device.

This solves the problem in case did something by accident. Seems legit! 

> 
> These would be two use cases:
> 
> * to calibrate permanently to 100%, attach 100% O2 flow to the opposite side and wait until both countdowns are over
> * to reset it to 21% air calibration after launching the device, attach any kind of flow to the opposite side, wait until first countdown is over, disconnect flow, restart device
> 
> .. what do you think?

Perfect! 

Next question: What if all goes wrong? Can we reset the flash? Quick research tells me: No. not possible, only by reflashing the firmware. Ok. Should we have a fallback solution? We have a temperature sensor too. Placing it in the fridge could reset it entirely ^^

**Comment by frauzufall** [comment]
Awesome feedback!

Regarding the engraving design - perfect, just how about aligning the first line left and the second line right (and maybe using the ascii arrows→ and ←)

Absolutely agree with taking an average measurement. Good point.

Resetting the flash, in my point of view, is the same as setting our permanent storage address to a default value (i.e. setting the factor to multiply `oxy_m` with to 1). This could happen each time right after a new calibration is performed. If the user decides to not permanently save the new calibration and only use it for the current runtime of the device, the flash is now back at the default value and after rebooting the device it will perform like it was factory reset.

**Comment by frauzufall** [comment]
Oh, and maybe we can engrave both sides of the device, because it can be used upside down if you rotate the display...

**Pull request merged**
